DROP TABLE IF EXISTS urls;
CREATE TABLE urls (
id INTEGER(4) NOT NULL AUTO_INCREMENT,
url VARCHAR(255),
site_name VARCHAR(255),
num INT(4),
regdate DATETIME,
PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET = utf8